services:
    tisseo.core_bundle.login.success.handler:
        class: Tisseo\CoreBundle\Security\Authentification\LoginSuccessHandler
        arguments:  ['@doctrine', '@router', '@session']

    form.type.tisseo_datepicker:
        class: Tisseo\CoreBundle\Form\Type\DatepickerType
        tags:
            - { name: form.type, alias: tisseo_datepicker }
    form.type.tisseo_tel:
        class: Tisseo\CoreBundle\Form\Type\TelType
        tags:
            - { name: form.type, alias: tisseo_tel }
    form.type.tisseo_email:
        class: Tisseo\CoreBundle\Form\Type\EmailType
        tags:
            - { name: form.type, alias: tisseo_email }
    form.type.tisseo_password:
        class: Tisseo\CoreBundle\Form\Type\PasswordType
        tags:
            - { name: form.type, alias: tisseo_password }
